apiVersion: v1
kind: Service
metadata:
  name: achat
spec:
  type: NodePort
  selector:
    app: achat
  ports:
    - protocol: TCP
      port: 8083           # Port sur lequel ton application écoute dans le conteneur
      targetPort: 8083      # Port exposé vers ton application
      nodePort: 30000      
